version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "8888:8888"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"